print("Welcome to the Band Name Generator")
print("What's name of your grew up in ?\n")
city_name=input()
print("What's your pet name ?\n")
pet_name=input()
print("Your band name could be " +  city_name + " " + pet_name)
